os: linux
language: php

# php:
#   - 5.6
#   - 7.2
#   - 7.3
#   - 7.4
  
services:
  - docker

before_install:
- docker build --no-cache -t outrise/webapp:${TRAVIS_COMMIT} .
# - docker run ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} /go/src/github.com/kainlite/whatismyip-go/whatismyip-go.test
- docker run -d -p 127.0.0.1:80:80 outrise/webapp:${TRAVIS_COMMIT}
- docker ps -a
script:
  - curl 127.0.0.1:80
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push outrise/webapp:${TRAVIS_COMMIT}

notifications: true

# deploy:
#   provider: pages:git
#   token: $GITHUB_P_TOKEN
#   edge: true
# deploy:
#   provider: script
#   script: bash docker_push
#   on:
#     branch: master

